=== systematic-chaos/ZygardeJobExecutor/src/main/resources/request/json-schema.json
{
    "id": "https://github.com/systematic-chaos/mbda-tfm",
    "$schema": "https://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "domain": {
            "type": "string",
            "enum": [
                "regression",
                "classification",
                "clustering",
                "deep-learning",
                "binomial-classification",
                "multinomial-classification",
                "misc-functions"
            ]
        },
        "dataset": {
        	"type": "object",
        	"properties": {
        		"path": {
        			"type": "string"
        		},
        		"format": {
        			"type": "string",
        			"enum": ["libsvm"]
        		}
        	},
        	"required": ["path"]
        },
        "methods": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "algorithm": {
                        "type": "string",
                        "enum": [
                        	"linear-regression",
                        	"generalized-linear-regression",
                        	"random-forest-regression",
                        	"decision-tree-regression",
                        	"gradient-boosted-tree-regression",
                        	"linear-support-vector-machine",
                        	"binomial-logistic-regression",
                        	"naive-bayes",
                        	"random-forest-classification",
                        	"multinomial-logistic-regression",
                        	"decision-tree-classification",
                        	"gradient-boosted-tree-classification",
                        	"k-means",
                        	"gaussian-mixture-model",
                        	"multilayer-perceptron-classifier",
                        	"branin"
                        ]
                    },
                    "hyperparameters": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "param": {
                                    "type": "string"
                                },
                                "values": {
                                    "type": "array",
                                    "items": {
                                        "type": [
                                            "number",
                                            "string"
                                        ]
                                    }
                                }
                            },
                            "required": [
                                "param",
                                "values"
                            ]
                        }
                    }
                },
                "required": [
                    "algorithm"
                ]
            },
            "uniqueItems": true
        },
        "parameterSearch": {
        	"type": "string",
        	"enum": [
        		"grid",
        		"random",
        		"bayesian-optimization"
        	]
        },
        "computationalResources": {
            "type": "object",
            "properties": {
                "instances": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "ec2Instance": {
                                "type": "string",
                                "pattern":"^[A-Za-z][0-9][a-z]?.(([1-9]{1,2}x)|x)?(nano|micro|small|medium|large|metal)$"
                            },
                            "additionalHardware": {
                                "type": "array",
                                "items": {
                                    "type": "string",
                                    "enum": [
                                        "GPU"
                                    ]
                                },
                                "uniqueItems": true
                            },
                            "minInstances": {
                                "type": "integer",
                                "minimum": 1,
                                "maximum": 32
                            },
                            "maxInstances": {
                                "type": "integer",
                                "minimum": 1,
                                "maximum": 32
                            }
                        }
                    }
                },
                "minTotalInstances": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 32
                },
                "maxTotalInstances": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 64
                }
            }
        },
        "emailAddress": {
            "type": "string",
            "format": "email"
        }
    },
    "required": [
        "domain",
        "methods",
        "emailAddress"
    ]
}

=== systematic-chaos/ZygardeJobExecutor/src/main/resources/request/generalized-linear-regression-request.json
{
	"domain": "regression",
	"methods": [
		{
			"algorithm": "generalized-linear-regression",
			"hyperparameters": [
				{
					"param": "maxIter",
					"values": [10, 25, 50, 100]
				},
				{
					"param": "regParam",
					"values": [0.0, 0.3]
				},
				{
					"param": "family",
					"values": ["gaussian", "binomial", "poisson", "gamma"]
				},
				{
					"param": "link",
					"values": ["identity", "log", "inverse", "logit", "probit", "cloglog", "sqrt"]
				}
			]
		}
	],
	"dataset": {
		"path": "s3a://zygarde-data/mllib/sample_linear_regression_data.txt",
		"format": "libsvm"
	},
	"parameterSearch": "random",
	"computationalResources": {
		"minTotalInstances": 1,
		"maxTotalInstances": 1
	},
	"emailAddress": "thanatos.dreamslayer@gmail.com"
}

=== systematic-chaos/ZygardeJobExecutor/src/main/resources/request/binomial-logistic-regression-request.json
{
	"domain": "classification",
	"methods": [
		{
			"algorithm": "binomial-logistic-regression",
			"hyperparameters": [
				{
					"param": "maxIter",
					"values": [10, 100]
				},
				{
					"param": "regParam",
					"values": [0.0, 0.01, 0.3]
				},
				{
					"param": "elasticNetParam",
					"values": [0.0, 0.8]
				}
			]
		}
	],
	"dataset": {
		"path": "s3a://zygarde-data/mllib/sample_libsvm_data.txt",
		"format": "libsvm"
	},
	"parameterSearch": "random",
	"computationalResources": {
		"minTotalInstances": 1,
		"maxTotalInstances": 1
	},
	"emailAddress": "thanatos.dreamslayer@gmail.com"
}

=== systematic-chaos/ZygardeJobExecutor/src/main/resources/request/multinomial-logistic-regression-request.json
{
	"domain": "classification",
	"methods": [
		{
			"algorithm": "multinomial-logistic-regression",
			"hyperparameters": [
				{
					"param": "maxIter",
					"values": [10, 100]
				},
				{
					"param": "regParam",
					"values": [0.0, 0.01, 0.3]
				},
				{
					"param": "elasticNetParam",
					"values": [0.0, 0.8]
				}
			]
		}
	],
	"dataset": {
		"path": "s3a://zygarde-data/mllib/sample_multiclass_classification_data.txt",
		"format": "libsvm"
	},
	"parameterSearch": "random",
	"computationalResources": {
		"minTotalInstances": 1,
		"maxTotalInstances": 1
	},
	"emailAddress": "thanatos.dreamslayer@gmail.com"
}

=== systematic-chaos/ZygardeJobExecutor/src/main/resources/request/gradient-boosted-tree-regression-request.json
{
	"domain": "regression",
	"methods": [
		{
			"algorithm": "gradient-boosted-tree-regression",
			"hyperparameters": [
				{
					"param": "maxIter",
					"values": [5, 20]
				},
				{
					"param": "maxDepth",
					"values": [2, 5]
				}
			]
		}
	],
	"dataset": {
		"path": "s3a://zygarde-data/mllib/sample_libsvm_data.txt",
		"format": "libsvm"
	},
	"parameterSearch": "random",
	"computationalResources": {
		"minTotalInstances": 1,
		"maxTotalInstances": 1
	},
	"emailAddress": "thanatos.dreamslayer@gmail.com"
}

=== systematic-chaos/ZygardeJobExecutor/src/main/resources/request/multilayer-perceptron-classifier-request.json
{
	"domain": "classification",
	"methods": [
		{
			"algorithm": "multilayer-perceptron-classifier",
			"hyperparameters": [
				{
					"param": "inputLayerWidth",
					"values": [2, 4]
				},
				{
					"param": "outputLayerWidth",
					"values": [2, 3]
				},
				{
					"param": "hiddenLayersWidth",
					"values": [2, 4, 5]
				},
				{
					"param": "numHiddenLayers",
					"values": [1, 2, 3]
				},
				{
					"param": "maxIter",
					"values": [100]
				},
				{
					"param": "blockSize",
					"values": [1, 128]
				}
			]
		}
	],
	"dataset": {
		"path": "/home/thanatos/workspace/JobExecutor/smac/data/mllib/sample_multiclass_classification_data.txt",
		"format": "libsvm"
	},
	"parameterSearch": "random",
	"computationalResources": {
		"minTotalInstances": 1,
		"maxTotalInstances": 1
	},
	"emailAddress": "thanatos.dreamslayer@gmail.com"
}
