=== systematic-chaos/ZygardeJobExecutor/src/main/resources/json-schema.json
{
    "id": "https://github.com/systematic-chaos/mbda-tfm",
    "$schema": "https://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "domain": {
            "type": "string",
            "enum": [
                "classification",
                "regression",
                "clustering",
                "deep-learning"
            ]
        },
        "methods": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "algorithm": {
                        "type": "string",
                        "enum": [
                            "decision-tree",
                            "svm",
                            "k-means",
                            "neural-network"
                        ]
                    },
                    "hyperparameters": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "param": {
                                    "type": "string"
                                },
                                "values": {
                                    "type": "array",
                                    "items": {
                                        "type": [
                                            "number",
                                            "string"
                                        ]
                                    }
                                }
                            },
                            "required": [
                                "param",
                                "values"
                            ]
                        },
                        "uniqueItems": true
                    }
                },
                "required": [
                    "algorithm"
                ]
            },
            "uniqueItems": true
        },
        "computationalResources": {
            "type": "object",
            "properties": {
                "instances": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "ec2Instance": {
                                "type": "string",
                                "pattern":"^[A-Za-z][0-9][a-z]?.(([1-9]{1,2}x)|x)?(nano|micro|small|medium|large|metal)$"
                            },
                            "additionalHardware": {
                                "type": "array",
                                "items": {
                                    "type": "string",
                                    "enum": [
                                        "GPU"
                                    ]
                                },
                                "uniqueItems": true
                            },
                            "minInstances": {
                                "type": "integer",
                                "minimum": 1,
                                "maximum": 32
                            },
                            "maxInstances": {
                                "type": "integer",
                                "minimum": 1,
                                "maximum": 32
                            }
                        }
                    }
                },
                "minTotalInstances": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 32
                },
                "maxTotalInstances": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 64
                }
            }
        },
        "emailAddress": {
            "type": "string",
            "format": "email"
        }
    },
    "required": [
        "domain",
        "methods",
        "emailAddress"
    ]
}

=== systematic-chaos/ZygardeJobExecutor/src/main/resources/request/request-smac.json
{
	"domain": "classification",
	"methods": [
		{
			"algorithm": "svm",
			"hyperparameters": [
				{
					"param": "x1",
					"values": [2.5, -5, 10, 0.397887, -3.14159, 3.14159, 9.42478]
				},
				{
					"param": "x2",
					"values": [7.5, 0, 15, 12.275, 2.275, 2.475, 0.397887]
				}
			]
		}
	],
	"computationalResources": {
		"maxTotalInstances": 6
	},
	"emailAddress": "thanatos.dreamslayer@gmail.com"
}

=== systematic-chaos/ZygardeJobExecutor/src/main/resources/request-body-full.json
{
	"domain": "regression",
	"methods": [
		{
			"algorithm": "svm",
			"hyperparameters": [
				{
					"param": "convergence",
					"values": [
						"fast",
						"slow"
					]
				}
			]
		},
		{
			"algorithm": "neural-network",
			"hyperparameters": [
				{
					"param": "numLayers",
					"values": [
						3,
						4,
						5,
						6
					]
				},
				{
					"param": "inputLayerWidth",
					"values": [
						8
					]
				},
				{
					"param": "hiddenLayersWidth",
					"values": [
						32
					]
				},
				{
					"param": "outputLayerWidth",
					"values": [
						4, 6, 8
					]
				}
			]
		},
		{
			"algorithm": "decision-tree"
		}
	],
	"computationalResources": {
		"instances": [
			{
				"ec2Instance": "t2.micro",
				"maxInstances": 4
			},
			{
				"ec2Instance": "m5.2xlarge",
				"additionalHardware": [
					"GPU"
				],
				"minInstances": 1,
				"maxInstances": 2
			}
		],
		"minTotalInstances": 1,
		"maxTotalInstances": 6
	},
	"emailAddress": "thanatos.dreamslayer@gmail.com"
}
